-- 0026_schedule_interval.sql
--
-- Issue #51: class schedules repeating every 1-4 weeks.
--
-- * classes.schedule_interval_weeks (1-4, default 1): one interval per class,
--   applying to all its weekdays. Every existing class gets 1, so its sessions
--   stay as they are (nothing is regenerated by this migration).
-- * A class day matches when its weekday is in the schedule, it lies within
--   from/until, and its ISO (Monday) week is a whole multiple of N weeks after
--   the ISO week of schedule_starts_on. The pattern is fixed to the calendar:
--   a cancelled day or holiday in an on-week loses that session and never
--   shifts later weeks.
-- * Changing the interval regenerates sessions like any other schedule change
--   (from today, Berlin; past, marked and extra sessions kept).
-- * set_class_schedule gains p_interval_weeks (default 1; 22023 outside 1-4).
--
-- Streaks (compute_student_streak, 0021) are untouched: they already count
-- only weeks in which one of the student's classes has a session, so off
-- weeks neither count nor break a streak.

-- ---------------------------------------------------------------------------
-- Column
-- ---------------------------------------------------------------------------

alter table public.classes
  add column schedule_interval_weeks smallint not null default 1,
  add constraint classes_schedule_interval_weeks_valid
    check (schedule_interval_weeks between 1 and 4);

comment on column public.classes.schedule_interval_weeks is
  'The schedule repeats every N weeks (1-4), counted from the ISO week of schedule_starts_on (issue #51). 1 = weekly.';

-- ---------------------------------------------------------------------------
-- Schedule matching (5-arg)
-- ---------------------------------------------------------------------------

create or replace function public.class_schedule_matches(
  p_day date,
  p_weekdays smallint[],
  p_starts_on date,
  p_ends_on date,
  p_interval_weeks integer
)
returns boolean
language sql
immutable
set search_path = public
as $$
  select extract(isodow from p_day)::smallint = any (p_weekdays)
    and p_day >= p_starts_on
    and (p_ends_on is null or p_day <= p_ends_on)
    and ((date_trunc('week', p_day::timestamp)::date
          - date_trunc('week', p_starts_on::timestamp)::date) / 7)
        % greatest(coalesce(p_interval_weeks, 1), 1) = 0;
$$;

comment on function public.class_schedule_matches(date, smallint[], date, date, integer) is
  'True when a class day falls on the schedule: weekday in p_weekdays, between p_starts_on and p_ends_on (inclusive; NULL end = open), and its ISO week a whole multiple of p_interval_weeks after the ISO week of p_starts_on (Story 6-4, issue #51).';

-- A new class day gets a session for every class whose schedule matches it.
create or replace function public.create_sessions_for_class_day()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.class_sessions (class_id, class_day_id)
  select c.id, new.id
  from public.classes c
  where public.class_schedule_matches(
    new.day, c.schedule_weekdays, c.schedule_starts_on, c.schedule_ends_on,
    c.schedule_interval_weeks
  )
  on conflict on constraint class_sessions_one_per_class_day do nothing;
  return new;
end;
$$;

-- A new class gets a session on every existing class day its schedule
-- matches (cancelled days included, so restoring such a day brings them back).
create or replace function public.create_sessions_for_class()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.class_sessions (class_id, class_day_id)
  select new.id, d.id
  from public.class_days d
  where public.class_schedule_matches(
    d.day, new.schedule_weekdays, new.schedule_starts_on, new.schedule_ends_on,
    new.schedule_interval_weeks
  )
  on conflict on constraint class_sessions_one_per_class_day do nothing;
  return new;
end;
$$;

-- Regenerates a class's sessions dated today (Berlin) or later after its
-- schedule changed (0021 body + interval).
create or replace function public.regenerate_class_sessions()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_today date := (now() at time zone 'Europe/Berlin')::date;
begin
  -- Future scheduled sessions that no longer match go; extras and sessions
  -- with attendance marks stay.
  delete from public.class_sessions s
  using public.class_days d
  where d.id = s.class_day_id
    and s.class_id = new.id
    and not s.extra
    and d.day >= v_today
    and not public.class_schedule_matches(
      d.day, new.schedule_weekdays, new.schedule_starts_on, new.schedule_ends_on,
      new.schedule_interval_weeks
    )
    and not exists (
      select 1 from public.attendance_records a where a.class_session_id = s.id
    );

  insert into public.class_sessions (class_id, class_day_id)
  select new.id, d.id
  from public.class_days d
  where d.day >= v_today
    and public.class_schedule_matches(
      d.day, new.schedule_weekdays, new.schedule_starts_on, new.schedule_ends_on,
      new.schedule_interval_weeks
    )
  on conflict on constraint class_sessions_one_per_class_day do nothing;

  return new;
end;
$$;

drop trigger if exists classes_regenerate_sessions on public.classes;
create trigger classes_regenerate_sessions
  after update of schedule_weekdays, schedule_starts_on, schedule_ends_on,
    schedule_interval_weeks on public.classes
  for each row
  execute function public.regenerate_class_sessions();

revoke all on function public.create_sessions_for_class_day() from public, anon, authenticated;
revoke all on function public.create_sessions_for_class() from public, anon, authenticated;
revoke all on function public.regenerate_class_sessions() from public, anon, authenticated;

-- The 4-arg matcher has no callers left.
drop function public.class_schedule_matches(date, smallint[], date, date);

-- ---------------------------------------------------------------------------
-- set_class_schedule (7-arg)
-- ---------------------------------------------------------------------------

drop function public.set_class_schedule(uuid, smallint[], time, integer, date, date);

create function public.set_class_schedule(
  p_class_id uuid,
  p_weekdays smallint[],
  p_start_time time,
  p_duration_minutes integer,
  p_starts_on date,
  p_ends_on date,
  p_interval_weeks integer default 1
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_weekdays smallint[];
begin
  if not (public.is_admin() or public.is_teacher_of_class(p_class_id)) then
    raise exception 'not allowed to edit this class''s schedule'
      using errcode = '42501';
  end if;

  select array_agg(distinct w order by w) into v_weekdays
  from unnest(p_weekdays) as w;

  if v_weekdays is null
    or array_position(v_weekdays, null) is not null
    or not (1 <= all (v_weekdays) and 7 >= all (v_weekdays)) then
    raise exception 'pick at least one weekday (1-7)' using errcode = '22023';
  end if;
  if p_starts_on is null then
    raise exception 'the schedule needs a start date' using errcode = '22023';
  end if;
  if p_ends_on is not null and p_ends_on < p_starts_on then
    raise exception 'the end date must be on or after the start date' using errcode = '22023';
  end if;
  if p_duration_minutes is not null and p_duration_minutes not between 15 and 480 then
    raise exception 'duration must be 15-480 minutes' using errcode = '22023';
  end if;
  if p_interval_weeks is null or p_interval_weeks not between 1 and 4 then
    raise exception 'the schedule repeats every 1-4 weeks' using errcode = '22023';
  end if;

  -- Sessions before today never change: a past session following the class
  -- time keeps the time it had, frozen into its own override, before the
  -- class time changes (a NULL old time stays NULL). Writes nothing when the
  -- time does not change.
  update public.class_sessions s
  set start_time_override = case
        when s.start_time_override is null
          and c.default_start_time is distinct from p_start_time
        then c.default_start_time
        else s.start_time_override
      end,
      duration_minutes_override = case
        when s.duration_minutes_override is null
          and c.default_duration_minutes is distinct from p_duration_minutes
        then c.default_duration_minutes
        else s.duration_minutes_override
      end
  from public.class_days d, public.classes c
  where d.id = s.class_day_id
    and c.id = s.class_id
    and s.class_id = p_class_id
    and d.day < (now() at time zone 'Europe/Berlin')::date
    and (
      (s.start_time_override is null
        and c.default_start_time is not null
        and c.default_start_time is distinct from p_start_time)
      or (s.duration_minutes_override is null
        and c.default_duration_minutes is not null
        and c.default_duration_minutes is distinct from p_duration_minutes)
    );

  -- Writing the schedule columns fires classes_regenerate_sessions.
  update public.classes
  set schedule_weekdays = v_weekdays,
      schedule_starts_on = p_starts_on,
      schedule_ends_on = p_ends_on,
      schedule_interval_weeks = p_interval_weeks::smallint,
      default_start_time = p_start_time,
      default_duration_minutes = p_duration_minutes
  where id = p_class_id;

  if not found then
    raise exception 'class not found' using errcode = 'P0002';
  end if;
end;
$$;

comment on function public.set_class_schedule(uuid, smallint[], time, integer, date, date, integer) is
  'Sets a class''s schedule (weekdays, start time, duration, start/end date, repeat every 1-4 weeks) and regenerates its sessions from today (Berlin) on (Story 6-4, issue #51). Past sessions keep their displayed time (frozen into their overrides). Admin or any teacher of the class.';

revoke all on function public.set_class_schedule(uuid, smallint[], time, integer, date, date, integer) from public, anon;
grant execute on function public.set_class_schedule(uuid, smallint[], time, integer, date, date, integer) to authenticated;
